### ISSUE TITLE
Add the pod!

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/march-2022-prep-portfolio#13]
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [ ] Replacing the images
- [ ] Update the names and locations of each fellow
- [ ] Update the pod number inside of `_config.yml`

**Comment by RishiKumarRay** [comment]
where can i find the members of pod

**Comment by wrussell1999** [comment]
Hey there! You'll get to meet all your pod members during today's kickoff
where everything will be explained to you!

If you have any additional questions, let us know!

**Comment by gnikita432** [comment]
Hey @wrussell1999 , Can I work on this issue?
And from where I will find the pod members' data?
